In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree    # Decision Tree
from sklearn.linear_model import LogisticRegression # LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC # Support Vector Machine 
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
import sklearn.feature_extraction.text as sk_text



## File Prep ##

In [2]:
%%time
column_names=['Name', 'ScreenName', 'UserID', 'FollowersCount', 'FriendsCount', 'Location', 'Description', 'CreatedAt', 'StatusID', 'Language', 'Place', 'RetweetCount', 'FavoriteCount', 'Text']
tweets = pd.read_csv('clinton_trump_tweets.txt', sep="\t",  encoding="ISO-8859-1", header=None, names=column_names)
#print initial data
tweets = tweets.drop(['ScreenName', 'FollowersCount', 'FriendsCount', 'CreatedAt', 'StatusID','Language', 'Place', 'RetweetCount', 'FavoriteCount'], axis=1)
tweets.Location = tweets.Location.astype(str)
tweets.Text = tweets.Text.astype(str)

ground_truth = pd.read_table('clinton_trump_user_classes.txt', encoding ="ISO-8859-1", dtype=int, names=["UserID", "TrumpOrClinton"])



CPU times: user 40.6 s, sys: 2.92 s, total: 43.6 s
Wall time: 45.8 s


### Task 1.1 (10 pts): Remove all retweets first. Remove all users that have less than 20 tweets. You may want to keep the entire tweet content, including hashtags/handles. ###

In [3]:
tweets = tweets[~tweets.Text.str.startswith('RT')]

In [4]:
%%time
def keepHashMentions(text):
    hashMentions = []
    for word in text:
        hashMentions.extend(word)
    return " ".join(hashMentions).strip()
## keeping tweet including hashtags and mentions here ## 
tweets['HashMentions'] = tweets.Text.str.findall('(@\w+)|(#\w+)').apply(keepHashMentions)


CPU times: user 13.7 s, sys: 314 ms, total: 14 s
Wall time: 13.8 s


### Remove all users that have less than 20 tweets. ###

In [5]:
#1.2 keep tweets where UID appears 20+ times
tweets = tweets.groupby("UserID").filter(lambda x: len(x) >= 20)

In [6]:
%%timeit
# Generate a list of mention/hashes that have a frequency of 20+ #
top_hash = pd.Series(tweets['HashMentions'].str.cat(sep=' ').split()).value_counts()
top20 = top_hash[top_hash>=20]
top20List = top20.index.tolist()

# Convert list to set so it will have quick lookup
top20Set = set(top20List)


# generate list of mention/hashes that occur 20+ times from our orginal list 
def removeUnder20Mentions(hashMentions):
    mentions =  hashMentions.split()
    mentionsOver20 = []
    for mention in mentions:
        if(mention in top20Set):
            mentionsOver20.append(mention)
    return " ".join(mentionsOver20)
tweets['HashMentions'] = tweets.HashMentions.apply(removeUnder20Mentions)

2.66 s ± 1.08 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
hashMentionsMerged = tweets.groupby('UserID')['HashMentions'].apply(' '.join).reset_index()
tweetsWithNoHashMentions = tweets.drop('HashMentions', axis=1)
tweets = pd.merge(tweetsWithNoHashMentions, hashMentionsMerged, on='UserID')
tweets = tweets.drop_duplicates('UserID')


In [8]:
#remove users that have no hashtag/handles
tweets = tweets[tweets.HashMentions.apply(lambda x:  bool(x and x.strip()))]


In [9]:
# Remove locations that are null 
tweets['LocationCleaned'] = tweets['Location'].apply(lambda x: x.split(',')[0])

tweetsLocations = tweets[tweets['Location'].notnull() & tweets['Description'].notnull()]
tweetsLocations = tweetsLocations[(tweetsLocations['LocationCleaned'] != 'nan') & (tweetsLocations['LocationCleaned'] != ' ') & (tweetsLocations['LocationCleaned'] != '')]

tweets = tweetsLocations[tweetsLocations['LocationCleaned'].isin(tweetsLocations['LocationCleaned'].value_counts().nlargest(150).index.tolist())]

# TODO: maybe try this later on with other locations
#tweetsLocations.LocationSplit = tweetsLocations.LocationSplit.map({'NYC':'New York','New York City':'New York','United States':'USA', "United States of America": 'USA'}).fillna(tweetsLocations.LocationSplit)




In [44]:
aggregateTweetsHashtags = tweets.groupby('UserID')['HashMentions'].apply(lambda x: x.str.cat(sep=' '))
tweetsPrepareSKText = pd.DataFrame({'User_id': aggregateTweetsHashtags.index, 'All_hashtags': aggregateTweetsHashtags.values})
vectorizer = sk_text.TfidfVectorizer(max_features = 1000,
                             #min_df=100, 
                             #max_df=.8,
                             stop_words = 'english'
                             )
matrix = vectorizer.fit_transform(tweetsPrepareSKText.All_hashtags.values)
tdidf = matrix.toarray()
df_text = pd.DataFrame(matrix.todense(), index=aggregateTweetsHashtags.index, columns=vectorizer.get_feature_names())
df_text.head()

039  0hour1__  100ktweets4safety   1a   2a  8217  8230  _kjrb_  \
UserID                                                                    
2391     0.0       0.0                0.0  0.0  0.0   0.0   0.0     0.0   
14763    0.0       0.0                0.0  0.0  0.0   0.0   0.0     0.0   
24263    0.0       0.0                0.0  0.0  0.0   0.0   0.0     0.0   
164833   0.0       0.0                0.0  0.0  0.0   0.0   0.0     0.0   
1026541  0.0       0.0                0.0  0.0  0.0   0.0   0.0     0.0   

         _makada_  abc     ...       wwe  wwiii  wyoming  xfactor  yahoonews  \
UserID                     ...                                                 
2391          0.0  0.0     ...       0.0    0.0      0.0      0.0        0.0   
14763         0.0  0.0     ...       0.0    0.0      0.0      0.0        0.0   
24263         0.0  0.0     ...       0.0    0.0      0.0      0.0        0.0   
164833        0.0  0.0     ...       0.0    0.0      0.0      0.0        0.0   
1026541       0.0  0.0     ...       0.0    0.0      0.0      0.0        0.0   

         yesursjewelry  youranonnews  youtube  yusufdfi  zekejmiller  
UserID                                                                
2391               0.0           0.0      0.0       0.0          0.0  
14763              0.0           0.0      0.0       0.0          0.0  
24263              0.0           0.0      0.0       0.0          0.0  
164833             0.0           0.0      0.0       0.0          0.0  
1026541            0.0           0.0      0.0       0.0          0.0  

[5 rows x 1000 columns]

### Vectorize Description ###

In [45]:
vectorizerDescription = sk_text.TfidfVectorizer(max_features = 1000,
                             #min_df=100, 
                             #max_df=.8,
                             stop_words = ['UserID']                
                            )

matrixDescription = vectorizerDescription.fit_transform(tweets.Description.values)
tdidfDescription = matrixDescription.toarray()
df_text_Description = pd.DataFrame(matrixDescription.todense(), index=tweets.UserID, columns=vectorizerDescription.get_feature_names())
df_text_Description.head()



/Users/jashmit/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['userid'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


10  100   11   12   14   15   16   17   18   19 ...   yet  yoga  \
UserID                                                       ...               
106568768   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0   0.0   
2447279666  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0   0.0   
231921777   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0   0.0   
201499452   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0   0.0   
17547533    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0   0.0   

            york  you  young  your  yours  youtube  youtuber  yrs  
UserID                                                             
106568768    0.0  0.0    0.0   0.0    0.0      0.0       0.0  0.0  
2447279666   0.0  0.0    0.0   0.0    0.0      0.0       0.0  0.0  
231921777    0.0  0.0    0.0   0.0    0.0      0.0       0.0  0.0  
201499452    0.0  0.0    0.0   0.0    0.0      0.0       0.0  0.0  
17547533     0.0  0.0    0.0   0.0    0.0      0.0       0.0  0.0  

[5 rows x 1000 columns]

### Vectorize Description ###

In [46]:
vectorizerLocation = sk_text.TfidfVectorizer(#max_features = 1000,
                             #min_df=100, 
                             #max_df=.8,
                             stop_words = ['UserID']                
                            )
matrixLocation = vectorizerLocation.fit_transform(tweets.LocationCleaned.values)
tdidfLocation = matrixDescription.toarray()
df_text_Location = pd.DataFrame(matrixLocation.todense(), index=tweets.UserID, columns=vectorizerLocation.get_feature_names())
df_text_Location.head()



africa  alabama  america  angeles  ann  antonio  arbor  area  \
UserID                                                                     
106568768      0.0      0.0      0.0      0.0  0.0      0.0    0.0   0.0   
2447279666     0.0      0.0      0.0      0.0  0.0      0.0    0.0   0.0   
231921777      0.0      0.0      0.0      0.0  0.0      0.0    0.0   0.0   
201499452      0.0      0.0      0.0      0.0  0.0      0.0    0.0   0.0   
17547533       0.0      0.0      0.0      0.0  0.0      0.0    0.0   0.0   

            arizona  arlington   ...     usa  vancouver  vegas  virginia  \
UserID                           ...                                       
106568768       0.0        0.0   ...     0.0        0.0    0.0       0.0   
2447279666      0.0        0.0   ...     1.0        0.0    0.0       0.0   
231921777       0.0        0.0   ...     0.0        0.0    0.0       0.0   
201499452       0.0        0.0   ...     0.0        0.0    0.0       0.0   
17547533        0.0        0.0   ...     0.0        0.0    0.0       0.0   

            washington  wisconsin  worldwide  worth      york  zealand  
UserID                                                                  
106568768          0.0        0.0        0.0    0.0  0.000000      0.0  
2447279666         0.0        0.0        0.0    0.0  0.000000      0.0  
231921777          0.0        0.0        0.0    0.0  0.000000      0.0  
201499452          0.0        0.0        0.0    0.0  0.534717      0.0  
17547533           0.0        0.0        0.0    0.0  0.000000      0.0  

[5 rows x 160 columns]

## Apply ground truths column to UserID of tweets Dataframe ##

In [47]:
#mergeGroundTruths = pd.merge(tweets, ground_truth, on = 'UserID')
#ground truth
dataFrameWithHashTagHandlesAndTruths = pd.merge(df_text,ground_truth, on = 'UserID')


##merge Description and Location into out dataframe 
dataFrameWithHashTagHandlesAndTruths = pd.merge(dataFrameWithHashTagHandlesAndTruths,df_text_Description,on = 'UserID')

dataFrameWithHashTagHandlesAndTruths = pd.merge(dataFrameWithHashTagHandlesAndTruths,df_text_Location,on = 'UserID')




## Implementing Logistic Regression on Location column, rest of models are below ##

### 1.1: Use train_test_split() to split data into training and test sets, where 20 percent of the records go to test set. ###

In [64]:
X = dataFrameWithHashTagHandlesAndTruths.drop(['UserID','TrumpOrClinton'], axis=1).head(4000)
# grabbing one of the location arrays: USA
y = dataFrameWithHashTagHandlesAndTruths.head(4000).TrumpOrClinton.values


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

# Task 1.2 (20 pts): Train Decision Tree, SVM, Logistic Regression, and Neural Networks #

## Decision Tree ##

In [65]:
## Decision tree boilerplate
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(metrics.precision_score(y_test, y_pred, average= 'weighted'))
print(metrics.recall_score(y_test, y_pred, average= 'weighted'))
print(metrics.f1_score(y_test, y_pred, average= 'weighted'))
print(metrics.confusion_matrix(y_test, y_pred))

0.6798973607038122
0.6775
0.6786617591121653
[[110 126]
 [132 432]]


## SVM ##

In [66]:
clf = SVC(C=1.0, gamma='auto') 
clf.fit(X_train, y_train) 
y_pred = clf.predict(X_test)

print(metrics.precision_score(y_test, y_pred, average= 'weighted'))
print(metrics.recall_score(y_test, y_pred, average= 'weighted'))
print(metrics.f1_score(y_test, y_pred, average= 'weighted'))
print(metrics.confusion_matrix(y_test, y_pred))

0.497025
0.705
0.5830205278592375
[[  0 236]
 [  0 564]]


/Users/jashmit/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/jashmit/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## LogisticRegression ##

In [67]:
logreg = LogisticRegression(solver='lbfgs') 
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)


print(metrics.precision_score(y_test, y_pred, average= 'weighted'))
print(metrics.recall_score(y_test, y_pred, average= 'weighted'))
print(metrics.f1_score(y_test, y_pred, average= 'weighted'))
print(metrics.confusion_matrix(y_test, y_pred))

0.769567235947604
0.78
0.7627521929824561
[[104 132]
 [ 44 520]]


## Nueral Networks ##

In [68]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

scaler = StandardScaler()
scaler.fit(X_train)
X_train= scaler.transform(X_train)
X_test = scaler.transform(X_test)

### Multilayer Perception Model: 30 30 30 is number of nerurons etc.
### Note: each feature does not have to have same number of neurons

In [ ]:
### hidden_layer_sizes: 3 hidden layers,  each has 30 neurons
### solver='adam' is a variation of gradient descent 
### max_iter determines the number of epochs

mlp = MLPClassifier(hidden_layer_sizes=(1000,1000,1000), solver='adam', max_iter=1000)

mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

In [ ]:
print(metrics.classification_report(y_test, y_pred))
print(metrics.precision_score(y_test, y_pred, average= 'weighted'))
print(metrics.recall_score(y_test, y_pred, average= 'weighted'))
print(metrics.f1_score(y_test, y_pred, average= 'weighted'))
print(metrics.confusion_matrix(y_test, y_pred, labels=[0, 1]))


              precision    recall  f1-score   support

           0       0.55      0.49      0.52       236
           1       0.80      0.83      0.81       564

   micro avg       0.73      0.73      0.73       800
   macro avg       0.67      0.66      0.67       800
weighted avg       0.72      0.73      0.73       800

0.7245625504439065
0.7325
0.7277163463406673
[[116 120]
 [ 94 470]]


# Task 1.3 (20 pts): Train k-NN model. In your report describe the features that you used for k-NN. Perform parameter tuning on k-NN model. Apply 5-fold cross validation and use grid search to find the best K value for k-NN model. Set scoring metric to F1 score (F-measure). Use the best K value identified from grid search to train your k-NN model. Plot the F1 score against K value based on the results you achieved from grid search. #

In [ ]:
%%time
# X_train = X_train[:2220]
# y_train = y_train[:2220]
# X_test = X_test[:555]
# y_test = y_test[:555]


param_grid = dict(n_neighbors=range(1,21))
knn = KNeighborsClassifier(n_neighbors=1)
grid = GridSearchCV(knn, param_grid, cv=5, scoring='f1_weighted',n_jobs=2)
grid.fit(X_train, y_train)
# view the complete results
means = grid.cv_results_['mean_test_score']

In [ ]:
import matplotlib.pyplot as plt
# plot the results
plt.plot(range(1,21),means)
plt.xlabel('Value of K for KNN')
plt.ylabel('F1 score based on Cross-Validation')
plt.show()

In [ ]:
# identify the best model
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

In [43]:
%%time
# train your model using all data and the best known parameters
#TODO: use best n_neighbors from grid search
knn = KNeighborsClassifier(n_neighbors=2, weights='uniform')
knn.fit(X_train, y_train)
y_pred =  knn.predict(X_test)

print(metrics.precision_score(y_test, y_pred, average= 'weighted'))
print(metrics.recall_score(y_test, y_pred, average= 'weighted'))
print(metrics.f1_score(y_test, y_pred, average= 'weighted'))
print(metrics.confusion_matrix(y_test, y_pred))

0.6130848355684858
0.6414414414414414
0.5678425708130891
[[ 29 175]
 [ 24 327]]
CPU times: user 12.1 s, sys: 96.1 ms, total: 12.2 s
Wall time: 12.3 s
